Output ./assets/vhs.gif

Require nvim
Require gum
Require ./nvd

Set Shell zsh
Set FontFamily Recursive
Set Framerate 20
Set FontSize 13
Set Width 1200
Set Height 675
Set Padding 10
Set Theme "Gruvbox Dark"

Type "./nvd --help"
Sleep 500ms
Enter
Sleep 500ms
Type "./nvd r"
Enter
Sleep 10ms
Type "nvchad"
Sleep 500ms
Enter
Sleep 2s
Type ":q"
Sleep 500ms
Enter
Sleep 500ms
Type "./nvd run"
Sleep 500ms
Enter
Sleep 500ms
Type "kic"
Sleep 500ms
Escape
Sleep 100ms
Type "./nvd install"
Sleep 500ms
Enter
Sleep 500ms
Type "git@github.com:nvim-lua/kickstart.nvim.git"
Sleep 500ms
Enter
Sleep 4s
Type "kickstart"
Sleep 300ms
Enter
Sleep 1s
Enter
Sleep 5s
Type "./nvd r"
Sleep 500ms
Enter
Sleep 500ms
Type "kick"
Sleep 500ms
Enter
Sleep 10s
Escape
Type ":q"
Sleep 500ms
Enter
Sleep 1s
